USE test;

DROP TABLE IF EXISTS `book`;

CREATE TABLE `book` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `description` varchar(255) NOT NULL,
  `author` varchar(100) NOT NULL,
  `isbn` varchar(20) NOT NULL,
  `print_year` int(11) NOT NULL,
  `read_already` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Origin', 'Robert Langdon, Harvard professor of symbology and religious iconology, arrives at the ultramodern Guggenheim Museum Bilbao to attend a major announcement—the unveiling of a discovery that “will change the face of science forever.”', 'Dan Brown', '978-0385514231', '2017', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('The Sun and Her Flowers', 'From Rupi Kaur, the #1 New York Times bestselling author of milk and honey, comes her long-awaited second collection of poetry.  A vibrant and transcendent journey about growth and healing.', 'Rupi Kaur', '978-1449486792', '2017', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('The Wisdom of Sundays', 'Oprah Winfrey says Super Soul Sunday is the television show she was born to do. “I see it as an offering,” she explains. “If you want to be more fully present and live your life with a wide-open heart.”', 'Oprah Winfrey', '978-1250138064', '2017', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Harry Potter and the Prisoner of Azkaban:', 'For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said.', 'J.K. Rowling', '978-0545791342', '1956', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('We Were Eight Years in Power', 'We were eight years in power” was the lament of Reconstruction-era black politicians as the American experiment in multiracial democracy ended with the return of white supremacist rule in the South. ', 'Ta-Nehisi Coates', '978-0399590566', '1994', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('What Happened', 'For the first time, Hillary Rodham Clinton reveals what she was thinking and feeling during one of the most controversial and unpredictable presidential elections in history. Now free from the constraints of running.', 'Hillary Rodham Clinton', '978-1501175565', '1884', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Magnus Chase and the Gods of Asgard', 'Magnus Chase, a once-homeless teen, is a resident of the Hotel Valhalla and one of Odin chosen warriors. As the son of Frey, the god of summer, fertility, and health, Magnus isnt naturally inclined to fighting.', 'Rick Riordan', '978-1423160939', '1968', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Dog Man: A Tale of Two Kitties: From the Creator of Captain', 'He was the best of dogs... He was the worst of dogs... It was the age of invention... It was the season of surprise... It was the eve of supa sadness... ', 'Dav Pilkey', '978-0545935210', '1975', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Milk and Honey', 'The book is divided into four chapters, and each chapter serves a different purpose. Deals with a different pain. Heals a different heartache. Milk and Honey takes readers through a journey of the most bitter moments/', 'Rupi Kaur', '978-1449474256', '1987', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Wonder', 'August Pullman was born with a facial difference that, up until now, has prevented him from going to a mainstream school. Starting 5th grade at Beecher Prep, he wants nothing more than to be treated as an ordinary kid—but his.', 'R. J. Palacio', '978-0375869020', '2000', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('The Getaway (Diary of a Wimpy Kid Book 12)', 'With the cold weather and the stress of the approaching holiday season, the Heffleys decide to escape to a tropical island resort for some much-needed rest and relaxation. A few days.', 'Jeff Kinney', '978-1419725456', '2005', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Killing England: The Brutal Struggle for American Independence', 'The breathtaking latest installment in Bill OReilly and Martin Duga mega-bestselling Killing series transports readers to the most important era in.', 'Bill Reilly', '978-1627790642', '2015', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Braving the Wilderness', 'True belonging doesnt require us to change who we are. It requires us to be who we are.” Social scientist Brene Brown, PhD, LMSW, has sparked a global conversation about the experiences that bring meaning to.', 'Brene Brown', '978-0812995848', '2008', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('The Legend of Zelda Encyclopedia', 'A comprehensive collection of enemies and items, potions to poes, an expansion of the lore touched upon in Hyrule Historia, concept art, screencaps, maps, main characters and how they relate, languages', 'Nintendo', '978-1506706382', '1997', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('It', 'Stephen Kings terrifying, classic #1 New York Times bestseller, “a landmark in American literature” (Chicago Sun-Times)—about seven adults who return to their hometown to confront a nightmare they had first stumbled on.', 'Stephen King', '978-1501175466', '1996', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Principles: Life and Work', 'In 1975, Ray Dalio founded an investment firm, Bridgewater Associates, out of his two-bedroom apartment in New York City. Forty years later, Bridgewater has made more money for its clients than any other.', 'Ray Dalio', '978-1501124020', '2015', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('The Subtle Art of Not Giving a F*ck', 'In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be "positive" all the time so that we can truly become better, happier people.', 'Mark Manson', '978-0062457714', '2012', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('The 5 Love Languages: The Secret to Love that Lasts', 'Falling in love is easy. Staying in love—thats the challenge. How can you keep your relationship fresh and growing amid the demands, conflicts, and just plain boredom of everyday life?', 'Gary Chapman', '978-0802412706', '2005', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('How to Win Friends', 'Dale Carnegies rock-solid, time-tested advice has carried countless people up the ladder of success in their business and personal lives. One of the most groundbreaking and timeless bestsellers of all time', 'Dale Carnegie', '978-0671027032', '2003', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('The TB12 Method', 'In modern sports, some athletes have managed to transcend their competition in a way that no one will ever forget: Jordan. Jeter. Ali. Williams. These elite legends have changed the game, achieved the unthinkable, and pushed.', 'Tom Brady', '978-1501180736', '2013', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('You Are a Badass', 'In this refreshingly entertaining how-to guide, bestselling author and world-traveling success coach, Jen Sincero, serves up 27 bitesized chapters full of hilariously inspiring stories, sage advice', 'Jen Sincero', '978-0762447695', '2007', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('The Instant Pot', 'If you own an Instant Pot®, you already know how amazing it is―and you are READY for an Instant Pot', 'Laurel Randolph', '978-1623156121', '2011', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Puppy Birthday to You!', 'Can the puppies from Nickelodeons PAW Patrol throw Chase a surprise birthday party AND save Adventure Bay? This action-packed Little Golden Book is sure to thrill boys and girls ages 2 to 5.', 'Golden Books', '978-0553522778', '1999', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Petty', 'No one other than Warren Zanes, rocker and writer and friend, could author a book about Tom Petty that is as honest and evocative of Pettys music and the remarkable rock and roll history he and his band helped to write.', 'Warren Zanes', '978-1250105196', '1995', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Sleeping Beauties', 'In a future so real and near it might be now, something happens when women go to sleep: they become shrouded in a cocoon-like gauze.', 'Stephen King', '978-1501163401', '1987', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('The Keto Reset Diet', 'Mounting scientific research is confirming that eating a ketogenic diet could represent one of the greatest nutritional breakthroughs of our time—and that it might be the healthiest and most effective weight loss strategy ever.', 'Mark Sisson', '978-1524762230', '2013', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('Daring to Hope: Finding God', 'When Katie Davis Majors moved to Uganda, accidentally founded a booming organization, and later became the mother of thirteen girls through the miracle of adoption, she determined to weave her.', 'Katie Davis Majors', '978-0735290518', '2004', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('High Performance Habits', 'After extensive original research and a decade as the worlds highest-paid performance coach, Brendon Burchard finally reveals the most effective habits for reaching long-term success.', 'Brendon Burchard', '978-1401952853', '2009', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('The Man Who Rediscovered God and Changed the World', 'On All Hallows Eve in 1517, a young monk named Martin Luther posted a document he hoped would spark an academic debate, but that instead ignited a conflagration that.', 'Eric Metaxas', '978-1101980019', '1994', '0');
INSERT INTO `test`.`book` (`title`, `description`, `author`, `isbn`, `print_year`, `read_already`) VALUES ('The Paradigm', 'Is it possible that there exists an ancient master blueprint that holds the secret behind the events of our times?', 'Jonathan Cahn', '978-1629994765', '1991', '0');
